name: .NET Build and Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  services:
    mssql:
      image: mcr.microsoft.com/mssql/server:2022-latest
      ports:
        - 1433:1433
      env:
        ACCEPT_EULA: Y
        SA_PASSWORD: "StrongPassw0rd!"
      options: >-
        --health-cmd="/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P 'StrongPassw0rd!' -Q 'SELECT 1'" 
        --health-interval=10s 
        --health-timeout=5s 
        --health-retries=5
    steps:
      - uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.15.0
      - name: Build
        run: dotnet build Balance/WebApp.csproj
      - name: Run migrations
        run: dotnet ef database update
      - name: Test
        run: dotnet test Balance.Tests/Balance.Tests.csproj