name: .NET Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/dotnet/sdk:8.0
    steps:
      - uses: actions/checkout@v4
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build

  test:
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/dotnet/sdk:8.0
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Restore dependencies
        run: dotnet restore
      - name: Test
        run: dotnet test
